/**
 * Recommendations module — static service categories + optional Claude blurbs.
 *
 * CATEGORIES is the canonical list. Each category has a generic description
 * that is shown without an API call. When ANTHROPIC_API_KEY is set, the
 * generateBlurbs() helper calls Claude Sonnet to produce a short, personalised
 * sentence for each category based on the buyer's profile.
 *
 * getOrGenerateBlurbs() wraps generateBlurbs() with a DB cache stored in
 * BuyerProfile.recommendationBlurbs — Claude is only called once per buyer
 * (or when preferences change and the cache is cleared externally).
 */
import Anthropic from "@anthropic-ai/sdk";
import { prisma } from "@/lib/prisma";

export interface RecommendationCategory {
  id: string;
  label: string;
  icon: string;
  genericDescription: string;
}

export interface Recommendation extends RecommendationCategory {
  /** Personalised blurb generated by Claude, or genericDescription if unavailable. */
  blurb: string;
}

export const CATEGORIES: RecommendationCategory[] = [
  {
    id: "legal",
    label: "Legal services",
    icon: "⚖",
    genericDescription:
      "A conveyancer or property solicitor handles contracts, title searches, and the legal handoff between buyer and seller.",
  },
  {
    id: "moving",
    label: "Moving & removals",
    icon: "🚚",
    genericDescription:
      "Professional movers cover packing, transport, and unpacking — especially useful for larger properties or tight timelines.",
  },
  {
    id: "insurance",
    label: "Home insurance",
    icon: "🏠",
    genericDescription:
      "Buildings and contents insurance is typically required from exchange of contracts. Compare quotes before completion.",
  },
  {
    id: "furniture",
    label: "Furniture & interiors",
    icon: "🛋",
    genericDescription:
      "New or second-hand furniture sourcing, interior design consultations, and fit-out services for your new home.",
  },
];

/**
 * Calls Claude to generate one short personalised sentence per category,
 * grounded in the buyer's profile preferences.
 *
 * Returns a map of categoryId → blurb.  Falls back gracefully: any
 * Claude error for a category returns its genericDescription instead.
 */
export async function generateBlurbs(
  preferences: Record<string, unknown>
): Promise<Map<string, string>> {
  const result = new Map<string, string>();
  const apiKey = process.env.ANTHROPIC_API_KEY;

  if (!apiKey) {
    CATEGORIES.forEach(c => result.set(c.id, c.genericDescription));
    return result;
  }

  const client = new Anthropic({ apiKey });

  const prompt = `A property buyer has the following profile:
${JSON.stringify(preferences, null, 2)}

For each of the following service categories, write ONE concise sentence (under 25 words) explaining specifically why this buyer should consider engaging that service, based on their situation. Be concrete, not generic.

Categories: legal, moving, insurance, furniture

Return ONLY valid JSON with this shape (no markdown, no explanation):
{
  "legal": "...",
  "moving": "...",
  "insurance": "...",
  "furniture": "..."
}`;

  try {
    const message = await client.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 512,
      messages: [{ role: "user", content: prompt }],
    });

    const block = message.content[0];
    if (block.type !== "text") throw new Error("Unexpected response type");

    const cleaned = block.text.trim().replace(/^```(?:json)?\n?/, "").replace(/\n?```$/, "");
    const parsed = JSON.parse(cleaned) as Record<string, string>;

    CATEGORIES.forEach(c => {
      result.set(c.id, typeof parsed[c.id] === "string" ? parsed[c.id] : c.genericDescription);
    });
  } catch {
    // On any failure fall back to generic descriptions
    CATEGORIES.forEach(c => result.set(c.id, c.genericDescription));
  }

  return result;
}

/**
 * Returns personalised recommendation blurbs for a buyer, using a DB cache.
 *
 * Flow:
 *  1. Load BuyerProfile.recommendationBlurbs — if present and valid JSON, return it.
 *  2. Call generateBlurbs(preferences) to get fresh blurbs from Claude (or generics).
 *  3. Persist the result back to BuyerProfile.recommendationBlurbs.
 *  4. Return the map.
 *
 * If the buyer has no profile (e.g. incomplete onboarding) this falls through
 * gracefully to generic blurbs without any DB write.
 */
export async function getOrGenerateBlurbs(
  userId: string,
  preferences: Record<string, unknown>
): Promise<Map<string, string>> {
  // 1. Check cache
  try {
    const profile = await prisma.buyerProfile.findUnique({
      where: { userId },
      select: { recommendationBlurbs: true },
    });

    if (profile?.recommendationBlurbs) {
      const cached = JSON.parse(profile.recommendationBlurbs) as Record<string, string>;
      const result = new Map<string, string>();
      let hit = true;
      CATEGORIES.forEach(c => {
        if (typeof cached[c.id] === "string") {
          result.set(c.id, cached[c.id]);
        } else {
          hit = false;
        }
      });
      if (hit) return result;
    }
  } catch {
    // non-fatal — proceed to generate
  }

  // 2. Generate
  const blurbs = await generateBlurbs(preferences);

  // 3. Persist if buyer has a profile
  try {
    const serialised: Record<string, string> = {};
    blurbs.forEach((v, k) => { serialised[k] = v; });

    await prisma.buyerProfile.updateMany({
      where: { userId },
      data: { recommendationBlurbs: JSON.stringify(serialised) },
    });
  } catch {
    // non-fatal — cache miss is acceptable
  }

  return blurbs;
}
